"""DuckDB meta information table functions.

Functions are extracted from DuckDB duckdb_functions() introspection.

This file is AUTO-GENERATED by `scripts/__main__.py`. DO NOT EDIT MANUALLY.
"""

from __future__ import annotations

from duckdb import table_function

from ._frame import LazyFrame


def approx_database_count(*args: object) -> LazyFrame:
    """SQL duckdb_approx_database_count table function.

    **SQL name**: *duckdb_approx_database_count*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_approx_database_count", *args))


def columns(*args: object) -> LazyFrame:
    """SQL duckdb_columns table function.

    **SQL name**: *duckdb_columns*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_columns", *args))


def connection_count(*args: object) -> LazyFrame:
    """SQL duckdb_connection_count table function.

    **SQL name**: *duckdb_connection_count*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_connection_count", *args))


def constraints(*args: object) -> LazyFrame:
    """SQL duckdb_constraints table function.

    **SQL name**: *duckdb_constraints*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_constraints", *args))


def coordinate_systems(*args: object) -> LazyFrame:
    """SQL duckdb_coordinate_systems table function.

    **SQL name**: *duckdb_coordinate_systems*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_coordinate_systems", *args))


def databases(*args: object) -> LazyFrame:
    """SQL duckdb_databases table function.

    **SQL name**: *duckdb_databases*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_databases", *args))


def dependencies(*args: object) -> LazyFrame:
    """SQL duckdb_dependencies table function.

    **SQL name**: *duckdb_dependencies*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_dependencies", *args))


def extensions(*args: object) -> LazyFrame:
    """SQL duckdb_extensions table function.

    **SQL name**: *duckdb_extensions*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_extensions", *args))


def external_file_cache(*args: object) -> LazyFrame:
    """SQL duckdb_external_file_cache table function.

    **SQL name**: *duckdb_external_file_cache*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_external_file_cache", *args))


def functions(*args: object) -> LazyFrame:
    """SQL duckdb_functions table function.

    **SQL name**: *duckdb_functions*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_functions", *args))


def indexes(*args: object) -> LazyFrame:
    """SQL duckdb_indexes table function.

    **SQL name**: *duckdb_indexes*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_indexes", *args))


def keywords(*args: object) -> LazyFrame:
    """SQL duckdb_keywords table function.

    **SQL name**: *duckdb_keywords*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_keywords", *args))


def log_contexts(*args: object) -> LazyFrame:
    """SQL duckdb_log_contexts table function.

    **SQL name**: *duckdb_log_contexts*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_log_contexts", *args))


def logs(denormalized_table: bool | None = None, *args: object) -> LazyFrame:  # noqa: FBT001
    """SQL duckdb_logs table function.

    **SQL name**: *duckdb_logs*

    Args:
        denormalized_table (bool | None): Parameter
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_logs", denormalized_table, *args))


def memory(*args: object) -> LazyFrame:
    """SQL duckdb_memory table function.

    **SQL name**: *duckdb_memory*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_memory", *args))


def optimizers(*args: object) -> LazyFrame:
    """SQL duckdb_optimizers table function.

    **SQL name**: *duckdb_optimizers*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_optimizers", *args))


def prepared_statements(*args: object) -> LazyFrame:
    """SQL duckdb_prepared_statements table function.

    **SQL name**: *duckdb_prepared_statements*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_prepared_statements", *args))


def schemas(*args: object) -> LazyFrame:
    """SQL duckdb_schemas table function.

    **SQL name**: *duckdb_schemas*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_schemas", *args))


def secret_types(*args: object) -> LazyFrame:
    """SQL duckdb_secret_types table function.

    **SQL name**: *duckdb_secret_types*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_secret_types", *args))


def secrets(redact: bool | None = None, *args: object) -> LazyFrame:  # noqa: FBT001
    """SQL duckdb_secrets table function.

    **SQL name**: *duckdb_secrets*

    Args:
        redact (bool | None): Parameter
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_secrets", redact, *args))


def sequences(*args: object) -> LazyFrame:
    """SQL duckdb_sequences table function.

    **SQL name**: *duckdb_sequences*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_sequences", *args))


def settings(*args: object) -> LazyFrame:
    """SQL duckdb_settings table function.

    **SQL name**: *duckdb_settings*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_settings", *args))


def tables(*args: object) -> LazyFrame:
    """SQL duckdb_tables table function.

    **SQL name**: *duckdb_tables*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_tables", *args))


def temporary_files(*args: object) -> LazyFrame:
    """SQL duckdb_temporary_files table function.

    **SQL name**: *duckdb_temporary_files*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_temporary_files", *args))


def types(*args: object) -> LazyFrame:
    """SQL duckdb_types table function.

    **SQL name**: *duckdb_types*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_types", *args))


def variables(*args: object) -> LazyFrame:
    """SQL duckdb_variables table function.

    **SQL name**: *duckdb_variables*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_variables", *args))


def views(*args: object) -> LazyFrame:
    """SQL duckdb_views table function.

    **SQL name**: *duckdb_views*

    Args:
        *args (object): Variable arguments

    Returns:
        LazyFrame
    """
    return LazyFrame(table_function("duckdb_views", *args))
