from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import pyochain as pc

from .._utils import CollectionsABC, DateTime, From, Pql, Typing
from ._rules import NAMESPACE_SPECS, NamespaceSpec


@dataclass(slots=True)
class FunctionInfo:
    """Container for pre-formatted function parts."""

    namespace: str | None
    python_name: str
    func: str


def build_file(fns: pc.Seq[FunctionInfo], path: Path) -> str:
    def _body(funcs: pc.Seq[FunctionInfo]) -> str:
        return funcs.then(
            lambda x: x.iter().map(lambda f: f.func).join("\n\n")
        ).unwrap_or("    pass")

    def _class_block(
        name: str,
        doc: str,
        funcs: pc.Seq[FunctionInfo],
        base: str,
        type_params: str | None = None,
    ) -> str:
        params = pc.Option(type_params).map(lambda tp: f"[{tp}]").unwrap_or("")
        return f'''
class {name}{params}({base}):
    __slots__ : ClassVar[Iterable[str]] = ()
    """{doc}"""
    {funcs.into(_body)}
'''

    def _namespace_block(spec: NamespaceSpec) -> str:
        return _class_block(
            spec.name,
            spec.doc,
            fns.iter().filter(lambda f: f.namespace == spec.name).collect(),
            "NameSpaceHandler[T]",
            "T: Fns",
        )

    base_fns = fns.iter().filter(lambda f: f.namespace is None).collect()
    doc = "Mixin providing auto-generated DuckDB functions as methods."
    return (
        f"{_header(path)}"
        f"{_class_block('Fns', doc, base_fns, 'DuckHandler')}"
        f"{NAMESPACE_SPECS.iter().map(_namespace_block).join('')}\n"
    )


def _header(path: Path) -> str:
    return f'''
"""DuckDB SQL function wrappers with type hints.

Functions are extracted from DuckDB duckdb_functions() introspection.

This file is AUTO-GENERATED by `{path.as_posix()}`. DO NOT EDIT MANUALLY.
"""

from __future__ import annotations
{From(CollectionsABC).import_(CollectionsABC.ITERABLE)}
{From(DateTime).import_(DateTime.DATE, DateTime.DATETIME, DateTime.TIME, DateTime.TIMEDELTA)}
{From(Typing).import_(Typing.SELF, Typing.TYPE_CHECKING, Typing.CLASSVAR)}

from sqlglot import exp

from .._core import DuckHandler, NameSpaceHandler, func, glot_func

if TYPE_CHECKING:
    from ..typing import SeqLiteral, {Pql.BLOB_LITERAL}, {Pql.INTO_EXPR_COLUMN}, {Pql.INTO_EXPR}
'''
